"""The rewrite must reproduce the original pandas-based pstats output.

Golden files were generated by the original pstats.py (commit 6d6dab5); the
original printed a trailing space on each line, which is ignored here.
"""

import pytest
from conftest import FIXTURES, GOLDEN

STATS = (GOLDEN / "STATS").read_text().split()


def _lines(text):
    return [line.rstrip() for line in text.splitlines()]


@pytest.mark.parametrize("name", ["small", "random", "single"])
def test_all_stats_match_original(run, name):
    code, out, _ = run(STATS, (FIXTURES / f"{name}.txt").read_text())
    assert code == 0
    assert _lines(out) == _lines((GOLDEN / f"{name}.out").read_text())


@pytest.mark.parametrize("name", ["small", "random", "single"])
def test_no_header_matches_original(run, name):
    code, out, _ = run(["-nh", "mean", "q25"], (FIXTURES / f"{name}.txt").read_text())
    assert code == 0
    assert _lines(out) == _lines((GOLDEN / f"{name}.nh.out").read_text())
